# Generated by Django 3.1.2 on 2020-10-26 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20201025_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='account_holder_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.AlterField(
            model_name='coins',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.customer'),
        ),
    ]
