# Generated by Django 3.1.2 on 2020-10-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20201026_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='userId',
            field=models.IntegerField(default=0),
        ),
    ]
