# Generated by Django 3.1.2 on 2020-10-27 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20201027_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='customer',
        ),
        migrations.AddField(
            model_name='bids',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.customer'),
        ),
    ]
