# Generated by Django 3.1.2 on 2020-10-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20201027_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='customer',
            name='account_holder_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='account_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='banks',
            field=models.CharField(choices=[('Capitec', 'Capitec'), ('Absa', 'Absa'), ('Nedbank', 'Nedbank'), ('Standard Bank', 'Standard_bank'), ('Tyme Bank', 'Tyme'), ('Bidvest', 'Bidvest'), ('African Bank', 'African_Bank'), ('Gro bank south Africa', 'Gro_bank_south_Africa'), ('FNB South Africa', 'FNB_South_Africa'), ('FNB Namibia', 'FNB_Namibia'), ('FNB South Africa', 'FNB_South_Africa'), ('FNB Swaziland', 'FNB_Swaziland'), ('FNB Zambia', 'FNB_Zambia')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
