# Generated by Django 3.1.2 on 2020-10-28 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20201029_0029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerBuy',
            new_name='BuyBid',
        ),
    ]
