# Generated by Django 3.1.2 on 2020-10-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20201029_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='bidremaining',
        ),
        migrations.AddField(
            model_name='bids',
            name='remainingbid',
            field=models.IntegerField(default=0),
        ),
    ]
