# Generated by Django 3.1.2 on 2020-10-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20201029_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='buybid',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
