# Generated by Django 3.1.2 on 2020-11-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20201030_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='remainingbid',
            field=models.IntegerField(default=0),
        ),
    ]
