# Generated by Django 3.1.3 on 2020-11-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20201102_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='buybid',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
