# Generated by Django 3.1.3 on 2020-11-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_immaturecoins'),
    ]

    operations = [
        migrations.AddField(
            model_name='buybid',
            name='days',
            field=models.CharField(choices=[('2', '2 Days'), ('5', '5 Days')], max_length=200, null=True),
        ),
    ]
